#############################################################################
# Makefile for building: AbFixedWingsSky
# Generated by qmake (3.1) (Qt 5.15.10)
# Project:  AbFixedWingsSky.pro
# Template: app
# Command: /home/ych/riscv-qt/bin/qmake -o Makefile AbFixedWingsSky.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = riscv64-unknown-linux-gnu-gcc
CXX           = riscv64-unknown-linux-gnu-g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -march=rv64g -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=rv64g -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include -I../riscv-qt/include -I../Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimediaWidgets -I../riscv-qt/include/QtMultimediaWidgets -I../Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimedia -I../riscv-qt/include/QtMultimedia -I../riscv-qt/include/QtNetwork -I../riscv-qt/include/QtWidgets -I../riscv-qt/include/QtGui -I../riscv-qt/include/QtCore -I. -I../riscv-qt/mkspecs/linux-riscv64-gnu-g++ -I/home/ych/Tina-Linux/out/d1-mq_pro/staging_dir/target/usr/include/ -I/home/ych/Tina-Linux/out/d1-mq_pro/staging_dir/target/usr/include/opencv4/ -I../riscv-wiringpi/include/
QMAKE         = /home/ych/riscv-qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/ych/riscv-qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/ych/riscv-qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AbFixedWingsSky1.0.0
DISTDIR = /home/ych/AbFixedWingsSky/.tmp/AbFixedWingsSky1.0.0
LINK          = riscv64-unknown-linux-gnu-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/home/ych/riscv-qt/lib -L/home/ych/riscv-wiringpi/lib -L/home/ych/Tina-Linux/out/d1-mq_pro/staging_dir/target/usr/lib/
LIBS          = $(SUBLIBS)  -lopencv_flann -lopencv_features2d -lopencv_calib3d -lpng12 -lwebp -lwiringPi -ljpeg -lz -lopencv_imgcodecs -lopencv_highgui -lopencv_core -lopencv_video -lopencv_videoio -lopencv_imgproc /home/ych/riscv-qt/lib/libQt5MultimediaWidgets.so /home/ych/riscv-qt/lib/libQt5Multimedia.so /home/ych/riscv-qt/lib/libQt5Network.so /home/ych/riscv-qt/lib/libQt5Widgets.so /home/ych/riscv-qt/lib/libQt5Gui.so /home/ych/riscv-qt/lib/libQt5Core.so -lpthread  -L/home/ych/Tina-Linux/out/d1-mq_pro/staging_dir/target/usr/lib/ -latomic -licuuc -licudata -licuio -licule -liculx -licui18n -lzstd 
AR            = riscv64-unknown-linux-gnu-ar cqs
RANLIB        = 
SED           = sed
STRIP         = riscv64-unknown-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		pt.cpp \
		receiverthr.cpp \
		udpreceiver.cpp moc_pt.cpp \
		moc_receiverthr.cpp \
		moc_udpreceiver.cpp
OBJECTS       = main.o \
		pt.o \
		receiverthr.o \
		udpreceiver.o \
		moc_pt.o \
		moc_receiverthr.o \
		moc_udpreceiver.o
DIST          = ../riscv-qt/mkspecs/features/spec_pre.prf \
		../riscv-qt/mkspecs/common/unix.conf \
		../riscv-qt/mkspecs/common/linux.conf \
		../riscv-qt/mkspecs/common/sanitize.conf \
		../riscv-qt/mkspecs/common/gcc-base.conf \
		../riscv-qt/mkspecs/common/gcc-base-unix.conf \
		../riscv-qt/mkspecs/common/g++-base.conf \
		../riscv-qt/mkspecs/common/g++-unix.conf \
		../riscv-qt/mkspecs/qconfig.pri \
		../riscv-qt/mkspecs/modules/qt_ext_freetype.pri \
		../riscv-qt/mkspecs/modules/qt_ext_libjpeg.pri \
		../riscv-qt/mkspecs/modules/qt_ext_libpng.pri \
		../riscv-qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_concurrent.pri \
		../riscv-qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_core.pri \
		../riscv-qt/mkspecs/modules/qt_lib_core_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_dbus.pri \
		../riscv-qt/mkspecs/modules/qt_lib_dbus_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_gui.pri \
		../riscv-qt/mkspecs/modules/qt_lib_gui_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_input_support_private.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimedia.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimedia_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_multimedia.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimediawidgets.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimediawidgets_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../riscv-qt/mkspecs/modules/qt_lib_network.pri \
		../riscv-qt/mkspecs/modules/qt_lib_network_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_printsupport.pri \
		../riscv-qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qml.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qml_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmltest.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_qtmultimediaquicktools_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quick.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quick_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_serialport.pri \
		../riscv-qt/mkspecs/modules/qt_lib_serialport_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_service_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_sql.pri \
		../riscv-qt/mkspecs/modules/qt_lib_sql_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_testlib.pri \
		../riscv-qt/mkspecs/modules/qt_lib_testlib_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_widgets.pri \
		../riscv-qt/mkspecs/modules/qt_lib_widgets_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_xml.pri \
		../riscv-qt/mkspecs/modules/qt_lib_xml_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_zlib_private.pri \
		../riscv-qt/mkspecs/features/qt_functions.prf \
		../riscv-qt/mkspecs/features/qt_config.prf \
		../riscv-qt/mkspecs/linux-riscv64-gnu-g++/qmake.conf \
		../riscv-qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../riscv-qt/mkspecs/features/exclusive_builds.prf \
		../riscv-qt/mkspecs/features/toolchain.prf \
		../riscv-qt/mkspecs/features/default_pre.prf \
		../riscv-qt/mkspecs/features/resolve_config.prf \
		../riscv-qt/mkspecs/features/default_post.prf \
		../riscv-qt/mkspecs/features/warn_on.prf \
		../riscv-qt/mkspecs/features/qt.prf \
		../riscv-qt/mkspecs/features/resources_functions.prf \
		../riscv-qt/mkspecs/features/resources.prf \
		../riscv-qt/mkspecs/features/moc.prf \
		../riscv-qt/mkspecs/features/uic.prf \
		../riscv-qt/mkspecs/features/unix/thread.prf \
		../riscv-qt/mkspecs/features/qmake_use.prf \
		../riscv-qt/mkspecs/features/file_copies.prf \
		../riscv-qt/mkspecs/features/testcase_targets.prf \
		../riscv-qt/mkspecs/features/exceptions.prf \
		../riscv-qt/mkspecs/features/yacc.prf \
		../riscv-qt/mkspecs/features/lex.prf \
		AbFixedWingsSky.pro pt.h \
		receiverthr.h \
		udpreceiver.h main.cpp \
		pt.cpp \
		receiverthr.cpp \
		udpreceiver.cpp
QMAKE_TARGET  = AbFixedWingsSky
DESTDIR       = 
TARGET        = AbFixedWingsSky


first: all
####### Build rules

AbFixedWingsSky:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AbFixedWingsSky.pro ../riscv-qt/mkspecs/linux-riscv64-gnu-g++/qmake.conf ../riscv-qt/mkspecs/features/spec_pre.prf \
		../riscv-qt/mkspecs/common/unix.conf \
		../riscv-qt/mkspecs/common/linux.conf \
		../riscv-qt/mkspecs/common/sanitize.conf \
		../riscv-qt/mkspecs/common/gcc-base.conf \
		../riscv-qt/mkspecs/common/gcc-base-unix.conf \
		../riscv-qt/mkspecs/common/g++-base.conf \
		../riscv-qt/mkspecs/common/g++-unix.conf \
		../riscv-qt/mkspecs/qconfig.pri \
		../riscv-qt/mkspecs/modules/qt_ext_freetype.pri \
		../riscv-qt/mkspecs/modules/qt_ext_libjpeg.pri \
		../riscv-qt/mkspecs/modules/qt_ext_libpng.pri \
		../riscv-qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_concurrent.pri \
		../riscv-qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_core.pri \
		../riscv-qt/mkspecs/modules/qt_lib_core_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_dbus.pri \
		../riscv-qt/mkspecs/modules/qt_lib_dbus_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_gui.pri \
		../riscv-qt/mkspecs/modules/qt_lib_gui_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_input_support_private.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimedia.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimedia_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_multimedia.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimediawidgets.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_multimediawidgets_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../riscv-qt/mkspecs/modules/qt_lib_network.pri \
		../riscv-qt/mkspecs/modules/qt_lib_network_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_printsupport.pri \
		../riscv-qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qml.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qml_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmltest.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../riscv-qt/mkspecs/modules-inst/qt_lib_qtmultimediaquicktools_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quick.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quick_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		../riscv-qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_serialport.pri \
		../riscv-qt/mkspecs/modules/qt_lib_serialport_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_service_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_sql.pri \
		../riscv-qt/mkspecs/modules/qt_lib_sql_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_testlib.pri \
		../riscv-qt/mkspecs/modules/qt_lib_testlib_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_widgets.pri \
		../riscv-qt/mkspecs/modules/qt_lib_widgets_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_xml.pri \
		../riscv-qt/mkspecs/modules/qt_lib_xml_private.pri \
		../riscv-qt/mkspecs/modules/qt_lib_zlib_private.pri \
		../riscv-qt/mkspecs/features/qt_functions.prf \
		../riscv-qt/mkspecs/features/qt_config.prf \
		../riscv-qt/mkspecs/linux-riscv64-gnu-g++/qmake.conf \
		../riscv-qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../riscv-qt/mkspecs/features/exclusive_builds.prf \
		../riscv-qt/mkspecs/features/toolchain.prf \
		../riscv-qt/mkspecs/features/default_pre.prf \
		../riscv-qt/mkspecs/features/resolve_config.prf \
		../riscv-qt/mkspecs/features/default_post.prf \
		../riscv-qt/mkspecs/features/warn_on.prf \
		../riscv-qt/mkspecs/features/qt.prf \
		../riscv-qt/mkspecs/features/resources_functions.prf \
		../riscv-qt/mkspecs/features/resources.prf \
		../riscv-qt/mkspecs/features/moc.prf \
		../riscv-qt/mkspecs/features/uic.prf \
		../riscv-qt/mkspecs/features/unix/thread.prf \
		../riscv-qt/mkspecs/features/qmake_use.prf \
		../riscv-qt/mkspecs/features/file_copies.prf \
		../riscv-qt/mkspecs/features/testcase_targets.prf \
		../riscv-qt/mkspecs/features/exceptions.prf \
		../riscv-qt/mkspecs/features/yacc.prf \
		../riscv-qt/mkspecs/features/lex.prf \
		AbFixedWingsSky.pro
	$(QMAKE) -o Makefile AbFixedWingsSky.pro
../riscv-qt/mkspecs/features/spec_pre.prf:
../riscv-qt/mkspecs/common/unix.conf:
../riscv-qt/mkspecs/common/linux.conf:
../riscv-qt/mkspecs/common/sanitize.conf:
../riscv-qt/mkspecs/common/gcc-base.conf:
../riscv-qt/mkspecs/common/gcc-base-unix.conf:
../riscv-qt/mkspecs/common/g++-base.conf:
../riscv-qt/mkspecs/common/g++-unix.conf:
../riscv-qt/mkspecs/qconfig.pri:
../riscv-qt/mkspecs/modules/qt_ext_freetype.pri:
../riscv-qt/mkspecs/modules/qt_ext_libjpeg.pri:
../riscv-qt/mkspecs/modules/qt_ext_libpng.pri:
../riscv-qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_concurrent.pri:
../riscv-qt/mkspecs/modules/qt_lib_concurrent_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_core.pri:
../riscv-qt/mkspecs/modules/qt_lib_core_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_dbus.pri:
../riscv-qt/mkspecs/modules/qt_lib_dbus_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_edid_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_fb_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_gui.pri:
../riscv-qt/mkspecs/modules/qt_lib_gui_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_input_support_private.pri:
../riscv-qt/mkspecs/modules-inst/qt_lib_multimedia.pri:
../riscv-qt/mkspecs/modules-inst/qt_lib_multimedia_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_multimedia.pri:
../riscv-qt/mkspecs/modules-inst/qt_lib_multimediawidgets.pri:
../riscv-qt/mkspecs/modules-inst/qt_lib_multimediawidgets_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
../riscv-qt/mkspecs/modules/qt_lib_network.pri:
../riscv-qt/mkspecs/modules/qt_lib_network_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_printsupport.pri:
../riscv-qt/mkspecs/modules/qt_lib_printsupport_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_qml.pri:
../riscv-qt/mkspecs/modules/qt_lib_qml_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_qmlmodels.pri:
../riscv-qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_qmltest.pri:
../riscv-qt/mkspecs/modules/qt_lib_qmltest_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../riscv-qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../riscv-qt/mkspecs/modules-inst/qt_lib_qtmultimediaquicktools_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_quick.pri:
../riscv-qt/mkspecs/modules/qt_lib_quick_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_quickwidgets.pri:
../riscv-qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_serialport.pri:
../riscv-qt/mkspecs/modules/qt_lib_serialport_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_service_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_sql.pri:
../riscv-qt/mkspecs/modules/qt_lib_sql_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_testlib.pri:
../riscv-qt/mkspecs/modules/qt_lib_testlib_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_theme_support_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_widgets.pri:
../riscv-qt/mkspecs/modules/qt_lib_widgets_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_xml.pri:
../riscv-qt/mkspecs/modules/qt_lib_xml_private.pri:
../riscv-qt/mkspecs/modules/qt_lib_zlib_private.pri:
../riscv-qt/mkspecs/features/qt_functions.prf:
../riscv-qt/mkspecs/features/qt_config.prf:
../riscv-qt/mkspecs/linux-riscv64-gnu-g++/qmake.conf:
../riscv-qt/mkspecs/features/spec_post.prf:
.qmake.stash:
../riscv-qt/mkspecs/features/exclusive_builds.prf:
../riscv-qt/mkspecs/features/toolchain.prf:
../riscv-qt/mkspecs/features/default_pre.prf:
../riscv-qt/mkspecs/features/resolve_config.prf:
../riscv-qt/mkspecs/features/default_post.prf:
../riscv-qt/mkspecs/features/warn_on.prf:
../riscv-qt/mkspecs/features/qt.prf:
../riscv-qt/mkspecs/features/resources_functions.prf:
../riscv-qt/mkspecs/features/resources.prf:
../riscv-qt/mkspecs/features/moc.prf:
../riscv-qt/mkspecs/features/uic.prf:
../riscv-qt/mkspecs/features/unix/thread.prf:
../riscv-qt/mkspecs/features/qmake_use.prf:
../riscv-qt/mkspecs/features/file_copies.prf:
../riscv-qt/mkspecs/features/testcase_targets.prf:
../riscv-qt/mkspecs/features/exceptions.prf:
../riscv-qt/mkspecs/features/yacc.prf:
../riscv-qt/mkspecs/features/lex.prf:
AbFixedWingsSky.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile AbFixedWingsSky.pro

qmake_all: FORCE


all: Makefile AbFixedWingsSky

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../riscv-qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents pt.h receiverthr.h udpreceiver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp pt.cpp receiverthr.cpp udpreceiver.cpp $(DISTDIR)/
	$(COPY_FILE) --parents AbFixedWingsSky_zh_CN.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../riscv-qt/mkspecs/features/data/dummy.cpp
	riscv64-unknown-linux-gnu-g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h ../riscv-qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_pt.cpp moc_receiverthr.cpp moc_udpreceiver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_pt.cpp moc_receiverthr.cpp moc_udpreceiver.cpp
moc_pt.cpp: pt.h \
		../riscv-qt/include/QtCore/QThread \
		../riscv-qt/include/QtCore/qthread.h \
		../riscv-qt/include/QtCore/qobject.h \
		../riscv-qt/include/QtCore/qobjectdefs.h \
		../riscv-qt/include/QtCore/qnamespace.h \
		../riscv-qt/include/QtCore/qglobal.h \
		../riscv-qt/include/QtCore/qconfig-bootstrapped.h \
		../riscv-qt/include/QtCore/qconfig.h \
		../riscv-qt/include/QtCore/qtcore-config.h \
		../riscv-qt/include/QtCore/qsystemdetection.h \
		../riscv-qt/include/QtCore/qprocessordetection.h \
		../riscv-qt/include/QtCore/qcompilerdetection.h \
		../riscv-qt/include/QtCore/qtypeinfo.h \
		../riscv-qt/include/QtCore/qsysinfo.h \
		../riscv-qt/include/QtCore/qlogging.h \
		../riscv-qt/include/QtCore/qflags.h \
		../riscv-qt/include/QtCore/qatomic.h \
		../riscv-qt/include/QtCore/qbasicatomic.h \
		../riscv-qt/include/QtCore/qatomic_bootstrap.h \
		../riscv-qt/include/QtCore/qgenericatomic.h \
		../riscv-qt/include/QtCore/qatomic_cxx11.h \
		../riscv-qt/include/QtCore/qatomic_msvc.h \
		../riscv-qt/include/QtCore/qglobalstatic.h \
		../riscv-qt/include/QtCore/qmutex.h \
		../riscv-qt/include/QtCore/qnumeric.h \
		../riscv-qt/include/QtCore/qversiontagging.h \
		../riscv-qt/include/QtCore/qobjectdefs_impl.h \
		../riscv-qt/include/QtCore/qstring.h \
		../riscv-qt/include/QtCore/qchar.h \
		../riscv-qt/include/QtCore/qbytearray.h \
		../riscv-qt/include/QtCore/qrefcount.h \
		../riscv-qt/include/QtCore/qarraydata.h \
		../riscv-qt/include/QtCore/qstringliteral.h \
		../riscv-qt/include/QtCore/qstringalgorithms.h \
		../riscv-qt/include/QtCore/qstringview.h \
		../riscv-qt/include/QtCore/qstringbuilder.h \
		../riscv-qt/include/QtCore/qlist.h \
		../riscv-qt/include/QtCore/qalgorithms.h \
		../riscv-qt/include/QtCore/qiterator.h \
		../riscv-qt/include/QtCore/qhashfunctions.h \
		../riscv-qt/include/QtCore/qpair.h \
		../riscv-qt/include/QtCore/qvector.h \
		../riscv-qt/include/QtCore/qcontainertools_impl.h \
		../riscv-qt/include/QtCore/qpoint.h \
		../riscv-qt/include/QtCore/qbytearraylist.h \
		../riscv-qt/include/QtCore/qstringlist.h \
		../riscv-qt/include/QtCore/qregexp.h \
		../riscv-qt/include/QtCore/qstringmatcher.h \
		../riscv-qt/include/QtCore/qcoreevent.h \
		../riscv-qt/include/QtCore/qscopedpointer.h \
		../riscv-qt/include/QtCore/qmetatype.h \
		../riscv-qt/include/QtCore/qvarlengtharray.h \
		../riscv-qt/include/QtCore/qcontainerfwd.h \
		../riscv-qt/include/QtCore/qobject_impl.h \
		../riscv-qt/include/QtCore/qdeadlinetimer.h \
		../riscv-qt/include/QtCore/qelapsedtimer.h \
		../riscv-qt/include/QtCore/QObject \
		../riscv-qt/include/QtWidgets/QWidget \
		../riscv-qt/include/QtWidgets/qwidget.h \
		../riscv-qt/include/QtWidgets/qtwidgetsglobal.h \
		../riscv-qt/include/QtGui/qtguiglobal.h \
		../riscv-qt/include/QtGui/qtgui-config.h \
		../riscv-qt/include/QtWidgets/qtwidgets-config.h \
		../riscv-qt/include/QtGui/qwindowdefs.h \
		../riscv-qt/include/QtGui/qwindowdefs_win.h \
		../riscv-qt/include/QtCore/qmargins.h \
		../riscv-qt/include/QtGui/qpaintdevice.h \
		../riscv-qt/include/QtCore/qrect.h \
		../riscv-qt/include/QtCore/qsize.h \
		../riscv-qt/include/QtGui/qpalette.h \
		../riscv-qt/include/QtGui/qcolor.h \
		../riscv-qt/include/QtGui/qrgb.h \
		../riscv-qt/include/QtGui/qrgba64.h \
		../riscv-qt/include/QtGui/qbrush.h \
		../riscv-qt/include/QtGui/qmatrix.h \
		../riscv-qt/include/QtGui/qpolygon.h \
		../riscv-qt/include/QtGui/qregion.h \
		../riscv-qt/include/QtCore/qdatastream.h \
		../riscv-qt/include/QtCore/qiodevice.h \
		../riscv-qt/include/QtCore/qline.h \
		../riscv-qt/include/QtGui/qtransform.h \
		../riscv-qt/include/QtGui/qimage.h \
		../riscv-qt/include/QtGui/qpixelformat.h \
		../riscv-qt/include/QtGui/qpixmap.h \
		../riscv-qt/include/QtCore/qsharedpointer.h \
		../riscv-qt/include/QtCore/qshareddata.h \
		../riscv-qt/include/QtCore/qhash.h \
		../riscv-qt/include/QtCore/qsharedpointer_impl.h \
		../riscv-qt/include/QtGui/qfont.h \
		../riscv-qt/include/QtGui/qfontmetrics.h \
		../riscv-qt/include/QtGui/qfontinfo.h \
		../riscv-qt/include/QtWidgets/qsizepolicy.h \
		../riscv-qt/include/QtGui/qcursor.h \
		../riscv-qt/include/QtGui/qkeysequence.h \
		../riscv-qt/include/QtGui/qevent.h \
		../riscv-qt/include/QtCore/qvariant.h \
		../riscv-qt/include/QtCore/qmap.h \
		../riscv-qt/include/QtCore/qdebug.h \
		../riscv-qt/include/QtCore/qtextstream.h \
		../riscv-qt/include/QtCore/qlocale.h \
		../riscv-qt/include/QtCore/qset.h \
		../riscv-qt/include/QtCore/qcontiguouscache.h \
		../riscv-qt/include/QtCore/qurl.h \
		../riscv-qt/include/QtCore/qurlquery.h \
		../riscv-qt/include/QtCore/qfile.h \
		../riscv-qt/include/QtCore/qfiledevice.h \
		../riscv-qt/include/QtGui/qvector2d.h \
		../riscv-qt/include/QtGui/qtouchdevice.h \
		../riscv-qt/include/QtNetwork/QTcpServer \
		../riscv-qt/include/QtNetwork/qtcpserver.h \
		../riscv-qt/include/QtNetwork/qtnetworkglobal.h \
		../riscv-qt/include/QtNetwork/qtnetwork-config.h \
		../riscv-qt/include/QtNetwork/qabstractsocket.h \
		../riscv-qt/include/QtNetwork/qhostaddress.h \
		../riscv-qt/include/QtNetwork/QTcpSocket \
		../riscv-qt/include/QtNetwork/qtcpsocket.h \
		../riscv-qt/include/QtCore/QBuffer \
		../riscv-qt/include/QtCore/qbuffer.h \
		../riscv-qt/include/QtCore/QFile \
		moc_predefs.h \
		../riscv-qt/bin/moc
	/home/ych/riscv-qt/bin/moc $(DEFINES) --include /home/ych/AbFixedWingsSky/moc_predefs.h -I/home/ych/riscv-qt/mkspecs/linux-riscv64-gnu-g++ -I/home/ych/AbFixedWingsSky -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include -I/home/ych/riscv-qt/include -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimediaWidgets -I/home/ych/riscv-qt/include/QtMultimediaWidgets -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimedia -I/home/ych/riscv-qt/include/QtMultimedia -I/home/ych/riscv-qt/include/QtNetwork -I/home/ych/riscv-qt/include/QtWidgets -I/home/ych/riscv-qt/include/QtGui -I/home/ych/riscv-qt/include/QtCore -I/usr/include/c++/11 -I/usr/include/riscv64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/riscv64-linux-gnu/11/include -I/usr/local/include -I/usr/include/riscv64-linux-gnu -I/usr/include pt.h -o moc_pt.cpp

moc_receiverthr.cpp: receiverthr.h \
		../riscv-qt/include/QtCore/QThread \
		../riscv-qt/include/QtCore/qthread.h \
		../riscv-qt/include/QtCore/qobject.h \
		../riscv-qt/include/QtCore/qobjectdefs.h \
		../riscv-qt/include/QtCore/qnamespace.h \
		../riscv-qt/include/QtCore/qglobal.h \
		../riscv-qt/include/QtCore/qconfig-bootstrapped.h \
		../riscv-qt/include/QtCore/qconfig.h \
		../riscv-qt/include/QtCore/qtcore-config.h \
		../riscv-qt/include/QtCore/qsystemdetection.h \
		../riscv-qt/include/QtCore/qprocessordetection.h \
		../riscv-qt/include/QtCore/qcompilerdetection.h \
		../riscv-qt/include/QtCore/qtypeinfo.h \
		../riscv-qt/include/QtCore/qsysinfo.h \
		../riscv-qt/include/QtCore/qlogging.h \
		../riscv-qt/include/QtCore/qflags.h \
		../riscv-qt/include/QtCore/qatomic.h \
		../riscv-qt/include/QtCore/qbasicatomic.h \
		../riscv-qt/include/QtCore/qatomic_bootstrap.h \
		../riscv-qt/include/QtCore/qgenericatomic.h \
		../riscv-qt/include/QtCore/qatomic_cxx11.h \
		../riscv-qt/include/QtCore/qatomic_msvc.h \
		../riscv-qt/include/QtCore/qglobalstatic.h \
		../riscv-qt/include/QtCore/qmutex.h \
		../riscv-qt/include/QtCore/qnumeric.h \
		../riscv-qt/include/QtCore/qversiontagging.h \
		../riscv-qt/include/QtCore/qobjectdefs_impl.h \
		../riscv-qt/include/QtCore/qstring.h \
		../riscv-qt/include/QtCore/qchar.h \
		../riscv-qt/include/QtCore/qbytearray.h \
		../riscv-qt/include/QtCore/qrefcount.h \
		../riscv-qt/include/QtCore/qarraydata.h \
		../riscv-qt/include/QtCore/qstringliteral.h \
		../riscv-qt/include/QtCore/qstringalgorithms.h \
		../riscv-qt/include/QtCore/qstringview.h \
		../riscv-qt/include/QtCore/qstringbuilder.h \
		../riscv-qt/include/QtCore/qlist.h \
		../riscv-qt/include/QtCore/qalgorithms.h \
		../riscv-qt/include/QtCore/qiterator.h \
		../riscv-qt/include/QtCore/qhashfunctions.h \
		../riscv-qt/include/QtCore/qpair.h \
		../riscv-qt/include/QtCore/qvector.h \
		../riscv-qt/include/QtCore/qcontainertools_impl.h \
		../riscv-qt/include/QtCore/qpoint.h \
		../riscv-qt/include/QtCore/qbytearraylist.h \
		../riscv-qt/include/QtCore/qstringlist.h \
		../riscv-qt/include/QtCore/qregexp.h \
		../riscv-qt/include/QtCore/qstringmatcher.h \
		../riscv-qt/include/QtCore/qcoreevent.h \
		../riscv-qt/include/QtCore/qscopedpointer.h \
		../riscv-qt/include/QtCore/qmetatype.h \
		../riscv-qt/include/QtCore/qvarlengtharray.h \
		../riscv-qt/include/QtCore/qcontainerfwd.h \
		../riscv-qt/include/QtCore/qobject_impl.h \
		../riscv-qt/include/QtCore/qdeadlinetimer.h \
		../riscv-qt/include/QtCore/qelapsedtimer.h \
		udpreceiver.h \
		../riscv-qt/include/QtCore/QObject \
		../riscv-qt/include/QtNetwork/QUdpSocket \
		../riscv-qt/include/QtNetwork/qudpsocket.h \
		../riscv-qt/include/QtNetwork/qtnetworkglobal.h \
		../riscv-qt/include/QtNetwork/qtnetwork-config.h \
		../riscv-qt/include/QtNetwork/qabstractsocket.h \
		../riscv-qt/include/QtCore/qiodevice.h \
		../riscv-qt/include/QtCore/qdebug.h \
		../riscv-qt/include/QtCore/qhash.h \
		../riscv-qt/include/QtCore/qmap.h \
		../riscv-qt/include/QtCore/qtextstream.h \
		../riscv-qt/include/QtCore/qlocale.h \
		../riscv-qt/include/QtCore/qvariant.h \
		../riscv-qt/include/QtCore/qshareddata.h \
		../riscv-qt/include/QtCore/qset.h \
		../riscv-qt/include/QtCore/qcontiguouscache.h \
		../riscv-qt/include/QtCore/qsharedpointer.h \
		../riscv-qt/include/QtCore/qsharedpointer_impl.h \
		../riscv-qt/include/QtNetwork/qhostaddress.h \
		moc_predefs.h \
		../riscv-qt/bin/moc
	/home/ych/riscv-qt/bin/moc $(DEFINES) --include /home/ych/AbFixedWingsSky/moc_predefs.h -I/home/ych/riscv-qt/mkspecs/linux-riscv64-gnu-g++ -I/home/ych/AbFixedWingsSky -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include -I/home/ych/riscv-qt/include -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimediaWidgets -I/home/ych/riscv-qt/include/QtMultimediaWidgets -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimedia -I/home/ych/riscv-qt/include/QtMultimedia -I/home/ych/riscv-qt/include/QtNetwork -I/home/ych/riscv-qt/include/QtWidgets -I/home/ych/riscv-qt/include/QtGui -I/home/ych/riscv-qt/include/QtCore -I/usr/include/c++/11 -I/usr/include/riscv64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/riscv64-linux-gnu/11/include -I/usr/local/include -I/usr/include/riscv64-linux-gnu -I/usr/include receiverthr.h -o moc_receiverthr.cpp

moc_udpreceiver.cpp: udpreceiver.h \
		../riscv-qt/include/QtCore/QObject \
		../riscv-qt/include/QtCore/qobject.h \
		../riscv-qt/include/QtCore/qobjectdefs.h \
		../riscv-qt/include/QtCore/qnamespace.h \
		../riscv-qt/include/QtCore/qglobal.h \
		../riscv-qt/include/QtCore/qconfig-bootstrapped.h \
		../riscv-qt/include/QtCore/qconfig.h \
		../riscv-qt/include/QtCore/qtcore-config.h \
		../riscv-qt/include/QtCore/qsystemdetection.h \
		../riscv-qt/include/QtCore/qprocessordetection.h \
		../riscv-qt/include/QtCore/qcompilerdetection.h \
		../riscv-qt/include/QtCore/qtypeinfo.h \
		../riscv-qt/include/QtCore/qsysinfo.h \
		../riscv-qt/include/QtCore/qlogging.h \
		../riscv-qt/include/QtCore/qflags.h \
		../riscv-qt/include/QtCore/qatomic.h \
		../riscv-qt/include/QtCore/qbasicatomic.h \
		../riscv-qt/include/QtCore/qatomic_bootstrap.h \
		../riscv-qt/include/QtCore/qgenericatomic.h \
		../riscv-qt/include/QtCore/qatomic_cxx11.h \
		../riscv-qt/include/QtCore/qatomic_msvc.h \
		../riscv-qt/include/QtCore/qglobalstatic.h \
		../riscv-qt/include/QtCore/qmutex.h \
		../riscv-qt/include/QtCore/qnumeric.h \
		../riscv-qt/include/QtCore/qversiontagging.h \
		../riscv-qt/include/QtCore/qobjectdefs_impl.h \
		../riscv-qt/include/QtCore/qstring.h \
		../riscv-qt/include/QtCore/qchar.h \
		../riscv-qt/include/QtCore/qbytearray.h \
		../riscv-qt/include/QtCore/qrefcount.h \
		../riscv-qt/include/QtCore/qarraydata.h \
		../riscv-qt/include/QtCore/qstringliteral.h \
		../riscv-qt/include/QtCore/qstringalgorithms.h \
		../riscv-qt/include/QtCore/qstringview.h \
		../riscv-qt/include/QtCore/qstringbuilder.h \
		../riscv-qt/include/QtCore/qlist.h \
		../riscv-qt/include/QtCore/qalgorithms.h \
		../riscv-qt/include/QtCore/qiterator.h \
		../riscv-qt/include/QtCore/qhashfunctions.h \
		../riscv-qt/include/QtCore/qpair.h \
		../riscv-qt/include/QtCore/qvector.h \
		../riscv-qt/include/QtCore/qcontainertools_impl.h \
		../riscv-qt/include/QtCore/qpoint.h \
		../riscv-qt/include/QtCore/qbytearraylist.h \
		../riscv-qt/include/QtCore/qstringlist.h \
		../riscv-qt/include/QtCore/qregexp.h \
		../riscv-qt/include/QtCore/qstringmatcher.h \
		../riscv-qt/include/QtCore/qcoreevent.h \
		../riscv-qt/include/QtCore/qscopedpointer.h \
		../riscv-qt/include/QtCore/qmetatype.h \
		../riscv-qt/include/QtCore/qvarlengtharray.h \
		../riscv-qt/include/QtCore/qcontainerfwd.h \
		../riscv-qt/include/QtCore/qobject_impl.h \
		../riscv-qt/include/QtNetwork/QUdpSocket \
		../riscv-qt/include/QtNetwork/qudpsocket.h \
		../riscv-qt/include/QtNetwork/qtnetworkglobal.h \
		../riscv-qt/include/QtNetwork/qtnetwork-config.h \
		../riscv-qt/include/QtNetwork/qabstractsocket.h \
		../riscv-qt/include/QtCore/qiodevice.h \
		../riscv-qt/include/QtCore/qdebug.h \
		../riscv-qt/include/QtCore/qhash.h \
		../riscv-qt/include/QtCore/qmap.h \
		../riscv-qt/include/QtCore/qtextstream.h \
		../riscv-qt/include/QtCore/qlocale.h \
		../riscv-qt/include/QtCore/qvariant.h \
		../riscv-qt/include/QtCore/qshareddata.h \
		../riscv-qt/include/QtCore/qset.h \
		../riscv-qt/include/QtCore/qcontiguouscache.h \
		../riscv-qt/include/QtCore/qsharedpointer.h \
		../riscv-qt/include/QtCore/qsharedpointer_impl.h \
		../riscv-qt/include/QtNetwork/qhostaddress.h \
		moc_predefs.h \
		../riscv-qt/bin/moc
	/home/ych/riscv-qt/bin/moc $(DEFINES) --include /home/ych/AbFixedWingsSky/moc_predefs.h -I/home/ych/riscv-qt/mkspecs/linux-riscv64-gnu-g++ -I/home/ych/AbFixedWingsSky -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include -I/home/ych/riscv-qt/include -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimediaWidgets -I/home/ych/riscv-qt/include/QtMultimediaWidgets -I/home/ych/Tina-Linux/qt-everywhere-src-5.15.10/qtmultimedia/include/QtMultimedia -I/home/ych/riscv-qt/include/QtMultimedia -I/home/ych/riscv-qt/include/QtNetwork -I/home/ych/riscv-qt/include/QtWidgets -I/home/ych/riscv-qt/include/QtGui -I/home/ych/riscv-qt/include/QtCore -I/usr/include/c++/11 -I/usr/include/riscv64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/riscv64-linux-gnu/11/include -I/usr/local/include -I/usr/include/riscv64-linux-gnu -I/usr/include udpreceiver.h -o moc_udpreceiver.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../riscv-qt/include/QtCore/QCoreApplication \
		../riscv-qt/include/QtCore/qcoreapplication.h \
		../riscv-qt/include/QtCore/qglobal.h \
		../riscv-qt/include/QtCore/qconfig-bootstrapped.h \
		../riscv-qt/include/QtCore/qconfig.h \
		../riscv-qt/include/QtCore/qtcore-config.h \
		../riscv-qt/include/QtCore/qsystemdetection.h \
		../riscv-qt/include/QtCore/qprocessordetection.h \
		../riscv-qt/include/QtCore/qcompilerdetection.h \
		../riscv-qt/include/QtCore/qtypeinfo.h \
		../riscv-qt/include/QtCore/qsysinfo.h \
		../riscv-qt/include/QtCore/qlogging.h \
		../riscv-qt/include/QtCore/qflags.h \
		../riscv-qt/include/QtCore/qatomic.h \
		../riscv-qt/include/QtCore/qbasicatomic.h \
		../riscv-qt/include/QtCore/qatomic_bootstrap.h \
		../riscv-qt/include/QtCore/qgenericatomic.h \
		../riscv-qt/include/QtCore/qatomic_cxx11.h \
		../riscv-qt/include/QtCore/qatomic_msvc.h \
		../riscv-qt/include/QtCore/qglobalstatic.h \
		../riscv-qt/include/QtCore/qmutex.h \
		../riscv-qt/include/QtCore/qnumeric.h \
		../riscv-qt/include/QtCore/qversiontagging.h \
		../riscv-qt/include/QtCore/qstring.h \
		../riscv-qt/include/QtCore/qchar.h \
		../riscv-qt/include/QtCore/qbytearray.h \
		../riscv-qt/include/QtCore/qrefcount.h \
		../riscv-qt/include/QtCore/qnamespace.h \
		../riscv-qt/include/QtCore/qarraydata.h \
		../riscv-qt/include/QtCore/qstringliteral.h \
		../riscv-qt/include/QtCore/qstringalgorithms.h \
		../riscv-qt/include/QtCore/qstringview.h \
		../riscv-qt/include/QtCore/qstringbuilder.h \
		../riscv-qt/include/QtCore/qobject.h \
		../riscv-qt/include/QtCore/qobjectdefs.h \
		../riscv-qt/include/QtCore/qobjectdefs_impl.h \
		../riscv-qt/include/QtCore/qlist.h \
		../riscv-qt/include/QtCore/qalgorithms.h \
		../riscv-qt/include/QtCore/qiterator.h \
		../riscv-qt/include/QtCore/qhashfunctions.h \
		../riscv-qt/include/QtCore/qpair.h \
		../riscv-qt/include/QtCore/qvector.h \
		../riscv-qt/include/QtCore/qcontainertools_impl.h \
		../riscv-qt/include/QtCore/qpoint.h \
		../riscv-qt/include/QtCore/qbytearraylist.h \
		../riscv-qt/include/QtCore/qstringlist.h \
		../riscv-qt/include/QtCore/qregexp.h \
		../riscv-qt/include/QtCore/qstringmatcher.h \
		../riscv-qt/include/QtCore/qcoreevent.h \
		../riscv-qt/include/QtCore/qscopedpointer.h \
		../riscv-qt/include/QtCore/qmetatype.h \
		../riscv-qt/include/QtCore/qvarlengtharray.h \
		../riscv-qt/include/QtCore/qcontainerfwd.h \
		../riscv-qt/include/QtCore/qobject_impl.h \
		../riscv-qt/include/QtCore/qeventloop.h \
		../riscv-qt/include/QtCore/QObject \
		../riscv-qt/include/QtCore/QtCore \
		../riscv-qt/include/QtCore/QtCoreDepends \
		../riscv-qt/include/QtCore/qabstractanimation.h \
		../riscv-qt/include/QtCore/qabstracteventdispatcher.h \
		../riscv-qt/include/QtCore/qabstractitemmodel.h \
		../riscv-qt/include/QtCore/qvariant.h \
		../riscv-qt/include/QtCore/qmap.h \
		../riscv-qt/include/QtCore/qdebug.h \
		../riscv-qt/include/QtCore/qhash.h \
		../riscv-qt/include/QtCore/qtextstream.h \
		../riscv-qt/include/QtCore/qiodevice.h \
		../riscv-qt/include/QtCore/qlocale.h \
		../riscv-qt/include/QtCore/qshareddata.h \
		../riscv-qt/include/QtCore/qset.h \
		../riscv-qt/include/QtCore/qcontiguouscache.h \
		../riscv-qt/include/QtCore/qsharedpointer.h \
		../riscv-qt/include/QtCore/qsharedpointer_impl.h \
		../riscv-qt/include/QtCore/qabstractnativeeventfilter.h \
		../riscv-qt/include/QtCore/qabstractproxymodel.h \
		../riscv-qt/include/QtCore/qabstractstate.h \
		../riscv-qt/include/QtCore/qabstracttransition.h \
		../riscv-qt/include/QtCore/qanimationgroup.h \
		../riscv-qt/include/QtCore/qarraydataops.h \
		../riscv-qt/include/QtCore/qarraydatapointer.h \
		../riscv-qt/include/QtCore/qbasictimer.h \
		../riscv-qt/include/QtCore/qbitarray.h \
		../riscv-qt/include/QtCore/qbuffer.h \
		../riscv-qt/include/QtCore/qbytearraymatcher.h \
		../riscv-qt/include/QtCore/qcache.h \
		../riscv-qt/include/QtCore/qcalendar.h \
		../riscv-qt/include/QtCore/qcborarray.h \
		../riscv-qt/include/QtCore/qcborvalue.h \
		../riscv-qt/include/QtCore/qdatetime.h \
		../riscv-qt/include/QtCore/qcborcommon.h \
		../riscv-qt/include/QtCore/qregularexpression.h \
		../riscv-qt/include/QtCore/qurl.h \
		../riscv-qt/include/QtCore/qurlquery.h \
		../riscv-qt/include/QtCore/quuid.h \
		../riscv-qt/include/QtCore/qcbormap.h \
		../riscv-qt/include/QtCore/qcborstream.h \
		../riscv-qt/include/QtCore/qcborstreamreader.h \
		../riscv-qt/include/QtCore/qfloat16.h \
		../riscv-qt/include/QtCore/qcborstreamwriter.h \
		../riscv-qt/include/QtCore/qcollator.h \
		../riscv-qt/include/QtCore/qcommandlineoption.h \
		../riscv-qt/include/QtCore/qcommandlineparser.h \
		../riscv-qt/include/QtCore/qconcatenatetablesproxymodel.h \
		../riscv-qt/include/QtCore/qcryptographichash.h \
		../riscv-qt/include/QtCore/qdatastream.h \
		../riscv-qt/include/QtCore/qdeadlinetimer.h \
		../riscv-qt/include/QtCore/qelapsedtimer.h \
		../riscv-qt/include/QtCore/qdir.h \
		../riscv-qt/include/QtCore/qfileinfo.h \
		../riscv-qt/include/QtCore/qfile.h \
		../riscv-qt/include/QtCore/qfiledevice.h \
		../riscv-qt/include/QtCore/qdiriterator.h \
		../riscv-qt/include/QtCore/qeasingcurve.h \
		../riscv-qt/include/QtCore/qendian.h \
		../riscv-qt/include/QtCore/qeventtransition.h \
		../riscv-qt/include/QtCore/qexception.h \
		../riscv-qt/include/QtCore/qfactoryinterface.h \
		../riscv-qt/include/QtCore/qfileselector.h \
		../riscv-qt/include/QtCore/QStringList \
		../riscv-qt/include/QtCore/qfilesystemwatcher.h \
		../riscv-qt/include/QtCore/qfinalstate.h \
		../riscv-qt/include/QtCore/qfuture.h \
		../riscv-qt/include/QtCore/qfutureinterface.h \
		../riscv-qt/include/QtCore/qrunnable.h \
		../riscv-qt/include/QtCore/qresultstore.h \
		../riscv-qt/include/QtCore/qfuturesynchronizer.h \
		../riscv-qt/include/QtCore/qfuturewatcher.h \
		../riscv-qt/include/QtCore/qhistorystate.h \
		../riscv-qt/include/QtCore/qidentityproxymodel.h \
		../riscv-qt/include/QtCore/qisenum.h \
		../riscv-qt/include/QtCore/qitemselectionmodel.h \
		../riscv-qt/include/QtCore/qjsonarray.h \
		../riscv-qt/include/QtCore/qjsonvalue.h \
		../riscv-qt/include/QtCore/qjsondocument.h \
		../riscv-qt/include/QtCore/qjsonobject.h \
		../riscv-qt/include/QtCore/qlibrary.h \
		../riscv-qt/include/QtCore/qlibraryinfo.h \
		../riscv-qt/include/QtCore/qversionnumber.h \
		../riscv-qt/include/QtCore/qline.h \
		../riscv-qt/include/QtCore/qlinkedlist.h \
		../riscv-qt/include/QtCore/qlockfile.h \
		../riscv-qt/include/QtCore/qloggingcategory.h \
		../riscv-qt/include/QtCore/qmargins.h \
		../riscv-qt/include/QtCore/qmath.h \
		../riscv-qt/include/QtCore/qmessageauthenticationcode.h \
		../riscv-qt/include/QtCore/qmetaobject.h \
		../riscv-qt/include/QtCore/qmimedata.h \
		../riscv-qt/include/QtCore/qmimedatabase.h \
		../riscv-qt/include/QtCore/qmimetype.h \
		../riscv-qt/include/QtCore/qobjectcleanuphandler.h \
		../riscv-qt/include/QtCore/qoperatingsystemversion.h \
		../riscv-qt/include/QtCore/qparallelanimationgroup.h \
		../riscv-qt/include/QtCore/qpauseanimation.h \
		../riscv-qt/include/QtCore/qplugin.h \
		../riscv-qt/include/QtCore/qpointer.h \
		../riscv-qt/include/QtCore/qpluginloader.h \
		../riscv-qt/include/QtCore/qprocess.h \
		../riscv-qt/include/QtCore/qpropertyanimation.h \
		../riscv-qt/include/QtCore/qvariantanimation.h \
		../riscv-qt/include/QtCore/qqueue.h \
		../riscv-qt/include/QtCore/qrandom.h \
		../riscv-qt/include/QtCore/qreadwritelock.h \
		../riscv-qt/include/QtCore/qrect.h \
		../riscv-qt/include/QtCore/qsize.h \
		../riscv-qt/include/QtCore/qresource.h \
		../riscv-qt/include/QtCore/qsavefile.h \
		../riscv-qt/include/QtCore/qscopedvaluerollback.h \
		../riscv-qt/include/QtCore/qscopeguard.h \
		../riscv-qt/include/QtCore/qsemaphore.h \
		../riscv-qt/include/QtCore/qsequentialanimationgroup.h \
		../riscv-qt/include/QtCore/qsettings.h \
		../riscv-qt/include/QtCore/qsharedmemory.h \
		../riscv-qt/include/QtCore/qsignalmapper.h \
		../riscv-qt/include/QtCore/qsignaltransition.h \
		../riscv-qt/include/QtCore/qsocketnotifier.h \
		../riscv-qt/include/QtCore/qsortfilterproxymodel.h \
		../riscv-qt/include/QtCore/qstack.h \
		../riscv-qt/include/QtCore/qstandardpaths.h \
		../riscv-qt/include/QtCore/qstate.h \
		../riscv-qt/include/QtCore/qstatemachine.h \
		../riscv-qt/include/QtCore/qstorageinfo.h \
		../riscv-qt/include/QtCore/qstringlistmodel.h \
		../riscv-qt/include/QtCore/qsystemsemaphore.h \
		../riscv-qt/include/QtCore/qtemporarydir.h \
		../riscv-qt/include/QtCore/qtemporaryfile.h \
		../riscv-qt/include/QtCore/qtextboundaryfinder.h \
		../riscv-qt/include/QtCore/qtextcodec.h \
		../riscv-qt/include/QtCore/qthread.h \
		../riscv-qt/include/QtCore/qthreadpool.h \
		../riscv-qt/include/QtCore/qthreadstorage.h \
		../riscv-qt/include/QtCore/qtimeline.h \
		../riscv-qt/include/QtCore/qtimer.h \
		../riscv-qt/include/QtCore/qtimezone.h \
		../riscv-qt/include/QtCore/qtranslator.h \
		../riscv-qt/include/QtCore/qtransposeproxymodel.h \
		../riscv-qt/include/QtCore/qtypetraits.h \
		../riscv-qt/include/QtCore/qwaitcondition.h \
		../riscv-qt/include/QtCore/QDeadlineTimer \
		../riscv-qt/include/QtCore/qwineventnotifier.h \
		../riscv-qt/include/QtCore/qxmlstream.h \
		../riscv-qt/include/QtCore/qtcoreversion.h \
		../riscv-qt/include/QtNetwork/QUdpSocket \
		../riscv-qt/include/QtNetwork/qudpsocket.h \
		../riscv-qt/include/QtNetwork/qtnetworkglobal.h \
		../riscv-qt/include/QtNetwork/qtnetwork-config.h \
		../riscv-qt/include/QtNetwork/qabstractsocket.h \
		../riscv-qt/include/QtNetwork/qhostaddress.h \
		pt.h \
		../riscv-qt/include/QtCore/QThread \
		../riscv-qt/include/QtWidgets/QWidget \
		../riscv-qt/include/QtWidgets/qwidget.h \
		../riscv-qt/include/QtWidgets/qtwidgetsglobal.h \
		../riscv-qt/include/QtGui/qtguiglobal.h \
		../riscv-qt/include/QtGui/qtgui-config.h \
		../riscv-qt/include/QtWidgets/qtwidgets-config.h \
		../riscv-qt/include/QtGui/qwindowdefs.h \
		../riscv-qt/include/QtGui/qwindowdefs_win.h \
		../riscv-qt/include/QtGui/qpaintdevice.h \
		../riscv-qt/include/QtGui/qpalette.h \
		../riscv-qt/include/QtGui/qcolor.h \
		../riscv-qt/include/QtGui/qrgb.h \
		../riscv-qt/include/QtGui/qrgba64.h \
		../riscv-qt/include/QtGui/qbrush.h \
		../riscv-qt/include/QtGui/qmatrix.h \
		../riscv-qt/include/QtGui/qpolygon.h \
		../riscv-qt/include/QtGui/qregion.h \
		../riscv-qt/include/QtGui/qtransform.h \
		../riscv-qt/include/QtGui/qimage.h \
		../riscv-qt/include/QtGui/qpixelformat.h \
		../riscv-qt/include/QtGui/qpixmap.h \
		../riscv-qt/include/QtGui/qfont.h \
		../riscv-qt/include/QtGui/qfontmetrics.h \
		../riscv-qt/include/QtGui/qfontinfo.h \
		../riscv-qt/include/QtWidgets/qsizepolicy.h \
		../riscv-qt/include/QtGui/qcursor.h \
		../riscv-qt/include/QtGui/qkeysequence.h \
		../riscv-qt/include/QtGui/qevent.h \
		../riscv-qt/include/QtGui/qvector2d.h \
		../riscv-qt/include/QtGui/qtouchdevice.h \
		../riscv-qt/include/QtNetwork/QTcpServer \
		../riscv-qt/include/QtNetwork/qtcpserver.h \
		../riscv-qt/include/QtNetwork/QTcpSocket \
		../riscv-qt/include/QtNetwork/qtcpsocket.h \
		../riscv-qt/include/QtCore/QBuffer \
		../riscv-qt/include/QtCore/QFile \
		udpreceiver.h \
		receiverthr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pt.o: pt.cpp pt.h \
		../riscv-qt/include/QtCore/QThread \
		../riscv-qt/include/QtCore/qthread.h \
		../riscv-qt/include/QtCore/qobject.h \
		../riscv-qt/include/QtCore/qobjectdefs.h \
		../riscv-qt/include/QtCore/qnamespace.h \
		../riscv-qt/include/QtCore/qglobal.h \
		../riscv-qt/include/QtCore/qconfig-bootstrapped.h \
		../riscv-qt/include/QtCore/qconfig.h \
		../riscv-qt/include/QtCore/qtcore-config.h \
		../riscv-qt/include/QtCore/qsystemdetection.h \
		../riscv-qt/include/QtCore/qprocessordetection.h \
		../riscv-qt/include/QtCore/qcompilerdetection.h \
		../riscv-qt/include/QtCore/qtypeinfo.h \
		../riscv-qt/include/QtCore/qsysinfo.h \
		../riscv-qt/include/QtCore/qlogging.h \
		../riscv-qt/include/QtCore/qflags.h \
		../riscv-qt/include/QtCore/qatomic.h \
		../riscv-qt/include/QtCore/qbasicatomic.h \
		../riscv-qt/include/QtCore/qatomic_bootstrap.h \
		../riscv-qt/include/QtCore/qgenericatomic.h \
		../riscv-qt/include/QtCore/qatomic_cxx11.h \
		../riscv-qt/include/QtCore/qatomic_msvc.h \
		../riscv-qt/include/QtCore/qglobalstatic.h \
		../riscv-qt/include/QtCore/qmutex.h \
		../riscv-qt/include/QtCore/qnumeric.h \
		../riscv-qt/include/QtCore/qversiontagging.h \
		../riscv-qt/include/QtCore/qobjectdefs_impl.h \
		../riscv-qt/include/QtCore/qstring.h \
		../riscv-qt/include/QtCore/qchar.h \
		../riscv-qt/include/QtCore/qbytearray.h \
		../riscv-qt/include/QtCore/qrefcount.h \
		../riscv-qt/include/QtCore/qarraydata.h \
		../riscv-qt/include/QtCore/qstringliteral.h \
		../riscv-qt/include/QtCore/qstringalgorithms.h \
		../riscv-qt/include/QtCore/qstringview.h \
		../riscv-qt/include/QtCore/qstringbuilder.h \
		../riscv-qt/include/QtCore/qlist.h \
		../riscv-qt/include/QtCore/qalgorithms.h \
		../riscv-qt/include/QtCore/qiterator.h \
		../riscv-qt/include/QtCore/qhashfunctions.h \
		../riscv-qt/include/QtCore/qpair.h \
		../riscv-qt/include/QtCore/qvector.h \
		../riscv-qt/include/QtCore/qcontainertools_impl.h \
		../riscv-qt/include/QtCore/qpoint.h \
		../riscv-qt/include/QtCore/qbytearraylist.h \
		../riscv-qt/include/QtCore/qstringlist.h \
		../riscv-qt/include/QtCore/qregexp.h \
		../riscv-qt/include/QtCore/qstringmatcher.h \
		../riscv-qt/include/QtCore/qcoreevent.h \
		../riscv-qt/include/QtCore/qscopedpointer.h \
		../riscv-qt/include/QtCore/qmetatype.h \
		../riscv-qt/include/QtCore/qvarlengtharray.h \
		../riscv-qt/include/QtCore/qcontainerfwd.h \
		../riscv-qt/include/QtCore/qobject_impl.h \
		../riscv-qt/include/QtCore/qdeadlinetimer.h \
		../riscv-qt/include/QtCore/qelapsedtimer.h \
		../riscv-qt/include/QtCore/QObject \
		../riscv-qt/include/QtWidgets/QWidget \
		../riscv-qt/include/QtWidgets/qwidget.h \
		../riscv-qt/include/QtWidgets/qtwidgetsglobal.h \
		../riscv-qt/include/QtGui/qtguiglobal.h \
		../riscv-qt/include/QtGui/qtgui-config.h \
		../riscv-qt/include/QtWidgets/qtwidgets-config.h \
		../riscv-qt/include/QtGui/qwindowdefs.h \
		../riscv-qt/include/QtGui/qwindowdefs_win.h \
		../riscv-qt/include/QtCore/qmargins.h \
		../riscv-qt/include/QtGui/qpaintdevice.h \
		../riscv-qt/include/QtCore/qrect.h \
		../riscv-qt/include/QtCore/qsize.h \
		../riscv-qt/include/QtGui/qpalette.h \
		../riscv-qt/include/QtGui/qcolor.h \
		../riscv-qt/include/QtGui/qrgb.h \
		../riscv-qt/include/QtGui/qrgba64.h \
		../riscv-qt/include/QtGui/qbrush.h \
		../riscv-qt/include/QtGui/qmatrix.h \
		../riscv-qt/include/QtGui/qpolygon.h \
		../riscv-qt/include/QtGui/qregion.h \
		../riscv-qt/include/QtCore/qdatastream.h \
		../riscv-qt/include/QtCore/qiodevice.h \
		../riscv-qt/include/QtCore/qline.h \
		../riscv-qt/include/QtGui/qtransform.h \
		../riscv-qt/include/QtGui/qimage.h \
		../riscv-qt/include/QtGui/qpixelformat.h \
		../riscv-qt/include/QtGui/qpixmap.h \
		../riscv-qt/include/QtCore/qsharedpointer.h \
		../riscv-qt/include/QtCore/qshareddata.h \
		../riscv-qt/include/QtCore/qhash.h \
		../riscv-qt/include/QtCore/qsharedpointer_impl.h \
		../riscv-qt/include/QtGui/qfont.h \
		../riscv-qt/include/QtGui/qfontmetrics.h \
		../riscv-qt/include/QtGui/qfontinfo.h \
		../riscv-qt/include/QtWidgets/qsizepolicy.h \
		../riscv-qt/include/QtGui/qcursor.h \
		../riscv-qt/include/QtGui/qkeysequence.h \
		../riscv-qt/include/QtGui/qevent.h \
		../riscv-qt/include/QtCore/qvariant.h \
		../riscv-qt/include/QtCore/qmap.h \
		../riscv-qt/include/QtCore/qdebug.h \
		../riscv-qt/include/QtCore/qtextstream.h \
		../riscv-qt/include/QtCore/qlocale.h \
		../riscv-qt/include/QtCore/qset.h \
		../riscv-qt/include/QtCore/qcontiguouscache.h \
		../riscv-qt/include/QtCore/qurl.h \
		../riscv-qt/include/QtCore/qurlquery.h \
		../riscv-qt/include/QtCore/qfile.h \
		../riscv-qt/include/QtCore/qfiledevice.h \
		../riscv-qt/include/QtGui/qvector2d.h \
		../riscv-qt/include/QtGui/qtouchdevice.h \
		../riscv-qt/include/QtNetwork/QTcpServer \
		../riscv-qt/include/QtNetwork/qtcpserver.h \
		../riscv-qt/include/QtNetwork/qtnetworkglobal.h \
		../riscv-qt/include/QtNetwork/qtnetwork-config.h \
		../riscv-qt/include/QtNetwork/qabstractsocket.h \
		../riscv-qt/include/QtNetwork/qhostaddress.h \
		../riscv-qt/include/QtNetwork/QTcpSocket \
		../riscv-qt/include/QtNetwork/qtcpsocket.h \
		../riscv-qt/include/QtCore/QBuffer \
		../riscv-qt/include/QtCore/qbuffer.h \
		../riscv-qt/include/QtCore/QFile
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pt.o pt.cpp

receiverthr.o: receiverthr.cpp receiverthr.h \
		../riscv-qt/include/QtCore/QThread \
		../riscv-qt/include/QtCore/qthread.h \
		../riscv-qt/include/QtCore/qobject.h \
		../riscv-qt/include/QtCore/qobjectdefs.h \
		../riscv-qt/include/QtCore/qnamespace.h \
		../riscv-qt/include/QtCore/qglobal.h \
		../riscv-qt/include/QtCore/qconfig-bootstrapped.h \
		../riscv-qt/include/QtCore/qconfig.h \
		../riscv-qt/include/QtCore/qtcore-config.h \
		../riscv-qt/include/QtCore/qsystemdetection.h \
		../riscv-qt/include/QtCore/qprocessordetection.h \
		../riscv-qt/include/QtCore/qcompilerdetection.h \
		../riscv-qt/include/QtCore/qtypeinfo.h \
		../riscv-qt/include/QtCore/qsysinfo.h \
		../riscv-qt/include/QtCore/qlogging.h \
		../riscv-qt/include/QtCore/qflags.h \
		../riscv-qt/include/QtCore/qatomic.h \
		../riscv-qt/include/QtCore/qbasicatomic.h \
		../riscv-qt/include/QtCore/qatomic_bootstrap.h \
		../riscv-qt/include/QtCore/qgenericatomic.h \
		../riscv-qt/include/QtCore/qatomic_cxx11.h \
		../riscv-qt/include/QtCore/qatomic_msvc.h \
		../riscv-qt/include/QtCore/qglobalstatic.h \
		../riscv-qt/include/QtCore/qmutex.h \
		../riscv-qt/include/QtCore/qnumeric.h \
		../riscv-qt/include/QtCore/qversiontagging.h \
		../riscv-qt/include/QtCore/qobjectdefs_impl.h \
		../riscv-qt/include/QtCore/qstring.h \
		../riscv-qt/include/QtCore/qchar.h \
		../riscv-qt/include/QtCore/qbytearray.h \
		../riscv-qt/include/QtCore/qrefcount.h \
		../riscv-qt/include/QtCore/qarraydata.h \
		../riscv-qt/include/QtCore/qstringliteral.h \
		../riscv-qt/include/QtCore/qstringalgorithms.h \
		../riscv-qt/include/QtCore/qstringview.h \
		../riscv-qt/include/QtCore/qstringbuilder.h \
		../riscv-qt/include/QtCore/qlist.h \
		../riscv-qt/include/QtCore/qalgorithms.h \
		../riscv-qt/include/QtCore/qiterator.h \
		../riscv-qt/include/QtCore/qhashfunctions.h \
		../riscv-qt/include/QtCore/qpair.h \
		../riscv-qt/include/QtCore/qvector.h \
		../riscv-qt/include/QtCore/qcontainertools_impl.h \
		../riscv-qt/include/QtCore/qpoint.h \
		../riscv-qt/include/QtCore/qbytearraylist.h \
		../riscv-qt/include/QtCore/qstringlist.h \
		../riscv-qt/include/QtCore/qregexp.h \
		../riscv-qt/include/QtCore/qstringmatcher.h \
		../riscv-qt/include/QtCore/qcoreevent.h \
		../riscv-qt/include/QtCore/qscopedpointer.h \
		../riscv-qt/include/QtCore/qmetatype.h \
		../riscv-qt/include/QtCore/qvarlengtharray.h \
		../riscv-qt/include/QtCore/qcontainerfwd.h \
		../riscv-qt/include/QtCore/qobject_impl.h \
		../riscv-qt/include/QtCore/qdeadlinetimer.h \
		../riscv-qt/include/QtCore/qelapsedtimer.h \
		udpreceiver.h \
		../riscv-qt/include/QtCore/QObject \
		../riscv-qt/include/QtNetwork/QUdpSocket \
		../riscv-qt/include/QtNetwork/qudpsocket.h \
		../riscv-qt/include/QtNetwork/qtnetworkglobal.h \
		../riscv-qt/include/QtNetwork/qtnetwork-config.h \
		../riscv-qt/include/QtNetwork/qabstractsocket.h \
		../riscv-qt/include/QtCore/qiodevice.h \
		../riscv-qt/include/QtCore/qdebug.h \
		../riscv-qt/include/QtCore/qhash.h \
		../riscv-qt/include/QtCore/qmap.h \
		../riscv-qt/include/QtCore/qtextstream.h \
		../riscv-qt/include/QtCore/qlocale.h \
		../riscv-qt/include/QtCore/qvariant.h \
		../riscv-qt/include/QtCore/qshareddata.h \
		../riscv-qt/include/QtCore/qset.h \
		../riscv-qt/include/QtCore/qcontiguouscache.h \
		../riscv-qt/include/QtCore/qsharedpointer.h \
		../riscv-qt/include/QtCore/qsharedpointer_impl.h \
		../riscv-qt/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o receiverthr.o receiverthr.cpp

udpreceiver.o: udpreceiver.cpp udpreceiver.h \
		../riscv-qt/include/QtCore/QObject \
		../riscv-qt/include/QtCore/qobject.h \
		../riscv-qt/include/QtCore/qobjectdefs.h \
		../riscv-qt/include/QtCore/qnamespace.h \
		../riscv-qt/include/QtCore/qglobal.h \
		../riscv-qt/include/QtCore/qconfig-bootstrapped.h \
		../riscv-qt/include/QtCore/qconfig.h \
		../riscv-qt/include/QtCore/qtcore-config.h \
		../riscv-qt/include/QtCore/qsystemdetection.h \
		../riscv-qt/include/QtCore/qprocessordetection.h \
		../riscv-qt/include/QtCore/qcompilerdetection.h \
		../riscv-qt/include/QtCore/qtypeinfo.h \
		../riscv-qt/include/QtCore/qsysinfo.h \
		../riscv-qt/include/QtCore/qlogging.h \
		../riscv-qt/include/QtCore/qflags.h \
		../riscv-qt/include/QtCore/qatomic.h \
		../riscv-qt/include/QtCore/qbasicatomic.h \
		../riscv-qt/include/QtCore/qatomic_bootstrap.h \
		../riscv-qt/include/QtCore/qgenericatomic.h \
		../riscv-qt/include/QtCore/qatomic_cxx11.h \
		../riscv-qt/include/QtCore/qatomic_msvc.h \
		../riscv-qt/include/QtCore/qglobalstatic.h \
		../riscv-qt/include/QtCore/qmutex.h \
		../riscv-qt/include/QtCore/qnumeric.h \
		../riscv-qt/include/QtCore/qversiontagging.h \
		../riscv-qt/include/QtCore/qobjectdefs_impl.h \
		../riscv-qt/include/QtCore/qstring.h \
		../riscv-qt/include/QtCore/qchar.h \
		../riscv-qt/include/QtCore/qbytearray.h \
		../riscv-qt/include/QtCore/qrefcount.h \
		../riscv-qt/include/QtCore/qarraydata.h \
		../riscv-qt/include/QtCore/qstringliteral.h \
		../riscv-qt/include/QtCore/qstringalgorithms.h \
		../riscv-qt/include/QtCore/qstringview.h \
		../riscv-qt/include/QtCore/qstringbuilder.h \
		../riscv-qt/include/QtCore/qlist.h \
		../riscv-qt/include/QtCore/qalgorithms.h \
		../riscv-qt/include/QtCore/qiterator.h \
		../riscv-qt/include/QtCore/qhashfunctions.h \
		../riscv-qt/include/QtCore/qpair.h \
		../riscv-qt/include/QtCore/qvector.h \
		../riscv-qt/include/QtCore/qcontainertools_impl.h \
		../riscv-qt/include/QtCore/qpoint.h \
		../riscv-qt/include/QtCore/qbytearraylist.h \
		../riscv-qt/include/QtCore/qstringlist.h \
		../riscv-qt/include/QtCore/qregexp.h \
		../riscv-qt/include/QtCore/qstringmatcher.h \
		../riscv-qt/include/QtCore/qcoreevent.h \
		../riscv-qt/include/QtCore/qscopedpointer.h \
		../riscv-qt/include/QtCore/qmetatype.h \
		../riscv-qt/include/QtCore/qvarlengtharray.h \
		../riscv-qt/include/QtCore/qcontainerfwd.h \
		../riscv-qt/include/QtCore/qobject_impl.h \
		../riscv-qt/include/QtNetwork/QUdpSocket \
		../riscv-qt/include/QtNetwork/qudpsocket.h \
		../riscv-qt/include/QtNetwork/qtnetworkglobal.h \
		../riscv-qt/include/QtNetwork/qtnetwork-config.h \
		../riscv-qt/include/QtNetwork/qabstractsocket.h \
		../riscv-qt/include/QtCore/qiodevice.h \
		../riscv-qt/include/QtCore/qdebug.h \
		../riscv-qt/include/QtCore/qhash.h \
		../riscv-qt/include/QtCore/qmap.h \
		../riscv-qt/include/QtCore/qtextstream.h \
		../riscv-qt/include/QtCore/qlocale.h \
		../riscv-qt/include/QtCore/qvariant.h \
		../riscv-qt/include/QtCore/qshareddata.h \
		../riscv-qt/include/QtCore/qset.h \
		../riscv-qt/include/QtCore/qcontiguouscache.h \
		../riscv-qt/include/QtCore/qsharedpointer.h \
		../riscv-qt/include/QtCore/qsharedpointer_impl.h \
		../riscv-qt/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpreceiver.o udpreceiver.cpp

moc_pt.o: moc_pt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pt.o moc_pt.cpp

moc_receiverthr.o: moc_receiverthr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_receiverthr.o moc_receiverthr.cpp

moc_udpreceiver.o: moc_udpreceiver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udpreceiver.o moc_udpreceiver.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/AbFixedWingsSky/bin || mkdir -p $(INSTALL_ROOT)/opt/AbFixedWingsSky/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/AbFixedWingsSky/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/AbFixedWingsSky/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/AbFixedWingsSky/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/AbFixedWingsSky/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

